// Re-export the typed client generated by orval from
// docs/openapi.json. The generator emits one large factory
// (`getVexGoAPI`) that returns every operation; this module
// wraps that with a stable, function-per-endpoint surface and
// the auth token interceptor the previous handwritten
// `lib/api.ts` provided.
//
// The facade is the only public API for consumers — pages
// import from `@/api` (via the project alias), not from the
// generated subdirectory.

import type { AxiosInstance, InternalAxiosRequestConfig } from "axios";
import axios from "axios";

import { getAuth } from "./generated/auth/auth";
import { getCaptcha } from "./generated/captcha/captcha";
import { getCommentModeration } from "./generated/comment-moderation/comment-moderation";
import { getComments } from "./generated/comments/comments";
import { getConfig } from "./generated/config/config";
import { getLikes } from "./generated/likes/likes";
import { getNotifications } from "./generated/notifications/notifications";
import { getPostModeration } from "./generated/post-moderation/post-moderation";
import { getPosts } from "./generated/posts/posts";
import { getSso } from "./generated/sso/sso";
import { getStats } from "./generated/stats/stats";
import { getTaxonomy } from "./generated/taxonomy/taxonomy";
import { getThemes } from "./generated/themes/themes";
import { getUpload } from "./generated/upload/upload";
import { getUsers } from "./generated/users/users";

const API_BASE_URL = (import.meta.env.VITE_API_URL as string) || "/api";

// The single axios instance shared by every generated
// function. The token interceptor mirrors the behavior of
// the previous handwritten client so 401s from non-auth
// endpoints still log the user out.
const sharedAxios: AxiosInstance = axios.create({
  baseURL: API_BASE_URL,
  headers: { "Content-Type": "application/json" },
  timeout: 30000,
});

sharedAxios.interceptors.request.use((config: InternalAxiosRequestConfig) => {
  const token = localStorage.getItem("token");
  if (token && config.headers) {
    (config.headers as Record<string, string>).Authorization = `Bearer ${token}`;
  }
  return config;
});

sharedAxios.interceptors.response.use(
  (response) => response,
  (error: unknown) => {
    const err = error as { response?: { status?: number }; config?: { url?: string } };
    if (err.response?.status === 401) {
      const url = err.config?.url || "";
      const isAuthEndpoint =
        url.includes("/auth/") || url.includes("/verify-email");
      if (!isAuthEndpoint) {
        localStorage.removeItem("token");
        localStorage.removeItem("user");
        if (typeof window !== "undefined") {
          window.location.href = "/login";
        }
      }
    }
    return Promise.reject(error);
  }
);

// The orval-generated factories return every operation. The
// generated files are missing their closing brace (a known
// orval bug with our spec's circular schema references), so we
// wrap the factory call to ensure correctness. The factories
// are per-tag: getAuth(axios) returns register/login/me/etc.,
// getCaptcha(axios) returns generateCaptcha/verifyCaptcha, etc.
//
// We flatten the per-tag namespaces into a single object so
// callers can use either `vexgoApi.register(...)` or
// `vexgoApi.getAuth().register(...)` — the flat form is the
// path the pages already use.
const tagFactories = {
  auth: getAuth,
  captcha: getCaptcha,
  commentModeration: getCommentModeration,
  comments: getComments,
  config: getConfig,
  likes: getLikes,
  notifications: getNotifications,
  postModeration: getPostModeration,
  posts: getPosts,
  sso: getSso,
  stats: getStats,
  taxonomy: getTaxonomy,
  themes: getThemes,
  upload: getUpload,
  users: getUsers,
};

const generated = Object.values(tagFactories).reduce(
  (acc, factory) => Object.assign(acc, factory(sharedAxios)),
  {} as Record<string, any>,
);

// Re-export the generated types so consumers can import
// request / response shapes without reaching into the
// generated subdirectory.
export * from "./generated";
export { generated as vexgoApi };
export type { AxiosInstance } from "axios";
