import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { notificationsApi, postsApi } from "@/lib/api";
import { useTranslation } from "@/lib/I18nContext";
import { CreatorApplicationButton } from "@/components/CreatorApplicationButton";
import type { Notification as BackendNotification } from "@/types";

import {
  Bell,
  MessageSquare,
  AlertCircle,
  UserPlus,
  CheckCircle,
  ThumbsUp,
  FileText,
  ArrowRight,
  Trash2,
  Eye,
  Users,
} from "lucide-react";

// Notification types
type NotificationType = "comment" | "like" | "reply" | "review" | "role";

type Notification = {
  id: string;
  type: NotificationType;
  title: string;
  content: string;
  relatedId: string;
  relatedType: "post" | "comment";
  relatedPostId: number | null;
  createdAt: string;
  isRead: boolean;
  sender?: {
    id: string;
    username: string;
    avatar?: string;
  };
};

export function NotificationCenterPage() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("all");

  // Notification data
  const [notifications, setNotifications] = useState<Notification[]>([]);

  const [loading, setLoading] = useState(false);

  // Check whether the user is an admin
  const isAdmin = user?.role === "admin" || user?.role === "super_admin";
  // Check whether the user is a guest
  const isGuest = user?.role === "guest";

  // Fetch notifications from the API
  useEffect(() => {
    const fetchNotifications = async () => {
      setLoading(true);
      try {
        const response = await notificationsApi.getNotifications();
        // Convert the backend data format to the frontend format. The
        // notification model shape is generated by tygo from the Go source.
        const formattedNotifications = response.data.notifications.map(
          (notification: BackendNotification) => ({
            id: notification.id.toString(),
            type: notification.type as NotificationType,
            title: notification.title,
            content: notification.content,
            relatedId: notification.related_id,
            relatedType: notification.related_type as "post" | "comment",
            relatedPostId: notification.related_post_id ?? null,
            createdAt: notification.created_at,
            isRead: notification.is_read,
            // The backend may not include sender info, so leave it empty for now
            sender: undefined,
          }),
        );
        setNotifications(formattedNotifications);
      } catch (error) {
        console.error(t("errors.networkError"), error);
      } finally {
        setLoading(false);
      }
    };

    fetchNotifications();
  }, [t]);

  // Filter notifications by tab
  const filteredNotifications = notifications.filter((notification) => {
    if (activeTab === "all") return true;
    if (activeTab === "unread") return !notification.isRead;
    if (activeTab === "comment")
      return notification.type === "comment" || notification.type === "reply";
    if (activeTab === "like") return notification.type === "like";
    if (activeTab === "review") return notification.type === "review";
    if (activeTab === "role") return notification.type === "role";
    return true;
  });

  // Mark a notification as read
  const markAsRead = async (id: string) => {
    try {
      await notificationsApi.markAsRead(id);
      // Update the local state
      setNotifications((prev) =>
        prev.map((notification) =>
          notification.id === id
            ? { ...notification, isRead: true }
            : notification,
        ),
      );
    } catch (error) {
      console.error(t("errors.networkError"), error);
    }
  };

  // Mark all as read
  const markAllAsRead = async () => {
    try {
      await notificationsApi.markAllAsRead();
      // Update the local state
      setNotifications((prev) =>
        prev.map((notification) => ({ ...notification, isRead: true })),
      );
    } catch (error) {
      console.error(t("errors.networkError"), error);
    }
  };

  // Delete a notification
  const deleteNotification = async (id: string) => {
    try {
      await notificationsApi.deleteNotification(id);
      // Update the local state
      setNotifications((prev) =>
        prev.filter((notification) => notification.id !== id),
      );
    } catch (error) {
      console.error(t("errors.networkError"), error);
    }
  };

  // Navigate to the related content
  const navigateToRelated = async (
    relatedId: string,
    relatedType: "post" | "comment",
    relatedPostId: number | null,
  ) => {
    // Resolve the post ID: for comment-related notifications use the
    // explicit post ID field; for post notifications relatedId is already
    // the post ID.
    const postId =
      relatedType === "comment" && relatedPostId != null
        ? String(relatedPostId)
        : relatedId;

    if (relatedType === "post") {
      try {
        const response = await postsApi.getPostById(postId);
        navigate(`/post/${response.data.post.slug}`);
      } catch {
        // Fallback: navigate with the ID (will be handled by the post page)
        navigate(`/post/by-id/${postId}`);
      }
    } else if (relatedType === "comment") {
      // Navigate to the post page and scroll to the comment
      try {
        const response = await postsApi.getPostById(postId);
        navigate(`/post/${response.data.post.slug}#comment-${relatedId}`);
      } catch {
        navigate(`/post/by-id/${postId}#comment-${relatedId}`);
      }
    }
  };

  // Get the status icon for a notification type
  const getStatusIcon = (type: NotificationType) => {
    switch (type) {
      case "review":
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      case "role":
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      default:
        return null;
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-2xl font-bold">{t("notificationCenter.title")}</h1>
        <div className="flex items-center gap-2">
          {isGuest && <CreatorApplicationButton />}
          {isAdmin && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => navigate("/admin/creator-applications")}
            >
              <Users className="w-4 h-4 mr-2" />
              {t("creatorApplication.reviewApplications")}
            </Button>
          )}
          <Button variant="outline" size="sm" onClick={markAllAsRead}>
            {t("notificationCenter.markAllAsRead")}
          </Button>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="mb-6">
          <TabsTrigger value="all">
            {t("notificationCenter.tabs.all")}
          </TabsTrigger>
          <TabsTrigger value="unread">
            {t("notificationCenter.tabs.unread")}
          </TabsTrigger>
          <TabsTrigger value="comment">
            {t("notificationCenter.tabs.comment")}
          </TabsTrigger>
          <TabsTrigger value="like">
            {t("notificationCenter.tabs.like")}
          </TabsTrigger>
          <TabsTrigger value="review">
            {t("notificationCenter.tabs.review")}
          </TabsTrigger>
          <TabsTrigger value="role">
            {t("notificationCenter.tabs.role")}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="all" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <Bell className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.noNotificationsDesc")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className={`cursor-pointer transition-all duration-200 hover:shadow-md ${notification.isRead ? "" : "border-l-4 border-primary"}`}
                onClick={() => {
                  markAsRead(notification.id);
                  if (notification.relatedId) {
                    navigateToRelated(
                      notification.relatedId,
                      notification.relatedType,
                      notification.relatedPostId,
                    );
                  }
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      {notification.sender ? (
                        <Avatar className="h-10 w-10">
                          <AvatarImage
                            src={notification.sender.avatar}
                            alt={notification.sender.username}
                          />
                          <AvatarFallback>
                            {notification.sender.username
                              .charAt(0)
                              .toUpperCase()}
                          </AvatarFallback>
                        </Avatar>
                      ) : (
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <AlertCircle className="w-5 h-5 text-primary" />
                        </div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          {!notification.isRead && (
                            <Badge variant="secondary" className="text-xs">
                              {t("notificationCenter.unreadBadge")}
                            </Badge>
                          )}
                          {getStatusIcon(notification.type)}
                        </div>
                        <div className="flex items-center gap-2">
                          {notification.type !== "role" && (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 px-2"
                              onClick={(e) => {
                                e.stopPropagation();
                                if (notification.relatedId) {
                                  navigateToRelated(
                                    notification.relatedId,
                                    notification.relatedType,
                                    notification.relatedPostId,
                                  );
                                }
                              }}
                            >
                              {t("notificationCenter.view")}{" "}
                              <ArrowRight className="w-3 h-3 ml-1" />
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteNotification(notification.id);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        {/* Other tab contents */}
        <TabsContent value="unread" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <Eye className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noUnreadNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.allRead")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className="border-l-4 border-primary cursor-pointer transition-all duration-200 hover:shadow-md"
                onClick={() => {
                  markAsRead(notification.id);
                  if (notification.relatedId) {
                    navigateToRelated(
                      notification.relatedId,
                      notification.relatedType,
                      notification.relatedPostId,
                    );
                  }
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      {notification.sender ? (
                        <Avatar className="h-10 w-10">
                          <AvatarImage
                            src={notification.sender.avatar}
                            alt={notification.sender.username}
                          />
                          <AvatarFallback>
                            {notification.sender.username
                              .charAt(0)
                              .toUpperCase()}
                          </AvatarFallback>
                        </Avatar>
                      ) : (
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <AlertCircle className="w-5 h-5 text-primary" />
                        </div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        <Badge variant="secondary" className="text-xs">
                          {t("notificationCenter.unreadBadge")}
                        </Badge>
                        <div className="flex items-center gap-2">
                          {notification.type !== "role" && (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 px-2"
                              onClick={(e) => {
                                e.stopPropagation();
                                if (notification.relatedId) {
                                  navigateToRelated(
                                    notification.relatedId,
                                    notification.relatedType,
                                    notification.relatedPostId,
                                  );
                                }
                              }}
                            >
                              {t("notificationCenter.view")}{" "}
                              <ArrowRight className="w-3 h-3 ml-1" />
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteNotification(notification.id);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="comment" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <MessageSquare className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noCommentNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.noCommentNotificationsDesc")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className={`cursor-pointer transition-all duration-200 hover:shadow-md ${notification.isRead ? "" : "border-l-4 border-primary"}`}
                onClick={() => {
                  markAsRead(notification.id);
                  if (notification.relatedId) {
                    navigateToRelated(
                      notification.relatedId,
                      notification.relatedType,
                      notification.relatedPostId,
                    );
                  }
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      {notification.sender ? (
                        <Avatar className="h-10 w-10">
                          <AvatarImage
                            src={notification.sender.avatar}
                            alt={notification.sender.username}
                          />
                          <AvatarFallback>
                            {notification.sender.username
                              .charAt(0)
                              .toUpperCase()}
                          </AvatarFallback>
                        </Avatar>
                      ) : (
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <MessageSquare className="w-5 h-5 text-primary" />
                        </div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        {!notification.isRead && (
                          <Badge variant="secondary" className="text-xs">
                            {t("notificationCenter.unreadBadge")}
                          </Badge>
                        )}
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={(e) => {
                              e.stopPropagation();
                              if (notification.relatedId) {
                                navigateToRelated(
                                  notification.relatedId,
                                  notification.relatedType,
                                  notification.relatedPostId,
                                );
                              }
                            }}
                          >
                            {t("notificationCenter.view")}{" "}
                            <ArrowRight className="w-3 h-3 ml-1" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteNotification(notification.id);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="like" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <ThumbsUp className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noLikeNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.noLikeNotificationsDesc")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className={`cursor-pointer transition-all duration-200 hover:shadow-md ${notification.isRead ? "" : "border-l-4 border-primary"}`}
                onClick={() => {
                  markAsRead(notification.id);
                  if (notification.relatedId) {
                    navigateToRelated(
                      notification.relatedId,
                      notification.relatedType,
                      notification.relatedPostId,
                    );
                  }
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      {notification.sender ? (
                        <Avatar className="h-10 w-10">
                          <AvatarImage
                            src={notification.sender.avatar}
                            alt={notification.sender.username}
                          />
                          <AvatarFallback>
                            {notification.sender.username
                              .charAt(0)
                              .toUpperCase()}
                          </AvatarFallback>
                        </Avatar>
                      ) : (
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <ThumbsUp className="w-5 h-5 text-primary" />
                        </div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        {!notification.isRead && (
                          <Badge variant="secondary" className="text-xs">
                            {t("notificationCenter.unreadBadge")}
                          </Badge>
                        )}
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={(e) => {
                              e.stopPropagation();
                              if (notification.relatedId) {
                                navigateToRelated(
                                  notification.relatedId,
                                  notification.relatedType,
                                  notification.relatedPostId,
                                );
                              }
                            }}
                          >
                            {t("notificationCenter.view")}{" "}
                            <ArrowRight className="w-3 h-3 ml-1" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteNotification(notification.id);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="review" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noReviewNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.noReviewNotificationsDesc")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className={`cursor-pointer transition-all duration-200 hover:shadow-md ${notification.isRead ? "" : "border-l-4 border-primary"}`}
                onClick={() => {
                  markAsRead(notification.id);
                  if (notification.relatedId) {
                    navigateToRelated(
                      notification.relatedId,
                      notification.relatedType,
                      notification.relatedPostId,
                    );
                  }
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                        <FileText className="w-5 h-5 text-primary" />
                      </div>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        {!notification.isRead && (
                          <Badge variant="secondary" className="text-xs">
                            {t("notificationCenter.unreadBadge")}
                          </Badge>
                        )}
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={(e) => {
                              e.stopPropagation();
                              if (notification.relatedId) {
                                navigateToRelated(
                                  notification.relatedId,
                                  notification.relatedType,
                                  notification.relatedPostId,
                                );
                              }
                            }}
                          >
                            {t("notificationCenter.view")}{" "}
                            <ArrowRight className="w-3 h-3 ml-1" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteNotification(notification.id);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="role" className="space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <UserPlus className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium mb-2">
                  {t("notificationCenter.empty.noRoleNotifications")}
                </h3>
                <p className="text-muted-foreground">
                  {t("notificationCenter.empty.noRoleNotificationsDesc")}
                </p>
              </CardContent>
            </Card>
          ) : (
            filteredNotifications.map((notification) => (
              <Card
                key={notification.id}
                className={`cursor-pointer transition-all duration-200 hover:shadow-md ${notification.isRead ? "" : "border-l-4 border-primary"}`}
                onClick={() => {
                  markAsRead(notification.id);
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                        <UserPlus className="w-5 h-5 text-primary" />
                      </div>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h3 className="font-medium text-sm">
                          {notification.title}
                        </h3>
                        <span className="text-xs text-muted-foreground">
                          {new Date(notification.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {notification.content}
                      </p>
                      <div className="flex items-center justify-between">
                        {!notification.isRead && (
                          <Badge variant="secondary" className="text-xs">
                            {t("notificationCenter.unreadBadge")}
                          </Badge>
                        )}
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-destructive"
                          onClick={(e) => {
                            e.stopPropagation();
                            deleteNotification(notification.id);
                          }}
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
