name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Set up pnpm
        uses: pnpm/setup@v1
        with:
          version: 11

      - name: Build frontend
        run: |
          cd frontend/
          pnpm install
          pnpm run build
          cd ..

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Install deadcode
        run: go install golang.org/x/tools/cmd/deadcode@latest

      - name: Install formatters
        run: |
          npm install prettier@3.9.6
          go install mvdan.cc/gofumpt@latest

      - name: Check Go formatting
        run: |
          files="$(gofumpt -l -extra .)"

          if [[ -n "$files" ]]; then
            echo "::error::unformatted files:"
            printf '%s\n' "$files"

            echo "::group::gofumpt diff"
            gofumpt -d -extra .
            echo "::endgroup::"

            exit 1
          fi

      - name: Check Prettier formatting
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,html,md}" "frontend/*.json" "./*.{json,yml,yaml}"

      - name: Run oxlint
        run: |
          cd frontend/
          pnpm run lint

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11

      - name: Run gopls
        run: |
          shopt -s globstar nullglob
          output="$(gopls check -severity=hint ./**/*.go)"

          if [[ -n "$output" ]]; then
            printf '%s\n' "$output"
            exit 1
          fi

      - name: Run deadcode
        run: |
          output=$(deadcode -test ./...); test -z "$output" || { echo "$output"; exit 1;}
